apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-server.fullname" . }}
  labels:
    {{- include "redis-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "redis-server.selectorLabels" . | nindent 4 }}
