name: 'Publish to S3'
description: 'Publish artifacts to S3 bucket'
inputs:
  aws_secret_access_key:
    description: AWS secret access key
    required: true
  aws_access_key:
    description: AWS access key
    required: true
  aws_s3_bucket_name:
    description: Name of the S3 bucket
    required: true
  repo_name:
    description: Combination of organization and repository (i.e. newrelic/nri-redis)
    required: true
  app_name:
    description: Name of the package (i.e. nri-redis)
    required: true
  tag:
    description: Tag pointing to the release
    required: true
runs:
  using: "composite"
  steps:
    - run: ./actions/publish/action-run-ohi.sh
      shell: bash