name: Publish pipeline

on:
  push:
    branches:
      - s3_publish_packages

env:
  AWS_SECRET: ${{ secrets.TEST_AWS_SECRET }}
  AWS_ACCESS_KEY: ${{ secrets.TEST_AWS_ACCESS_KEY }}
  AWS_BUCKET: ${{ secrets.TEST_AWS_BUCKET }}
  AWS_MOUNT_POINT: "/var/www/s3"


jobs:

  publish:
    name: Publish artifacts to s3
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      - name: Publish to S3 action
        uses: ./
