name: Publish pipeline

on:
  push:
    branches:
      - s3_publish_packages

env:
  DOCKER_HUB_ID: ${{ secrets.OHAI_DOCKER_HUB_ID }}
  DOCKER_HUB_PASSWORD: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}

jobs:

  publish:
    name: Publish artifacts to s3
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      - name: Publish to S3 action
        uses: ./actions/publish
        with:
          aws_secret_access_key: ${{ secrets.TEST_AWS_SECRET }}
          aws_access_key: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws_s3_bucket_name: ${{ secrets.TEST_AWS_BUCKET }}
          tag: "v1.6.0"
          app_name: "nri-redis"
          repo_name: "newrelic/nri-redis"
